### ISSUE TITLE
Todo: create and implement a logger system

### ISSUE THREAD

**Issue by NukeZzZin** [NukeZzZin/Perona#5]
**Todo:** Create and implement a logger system

establish a robust logging system for the application to ensure better tracking and analysis of events. This will help us in debugging and monitoring the system effectively.

**Tasks:**
- [x] Make a basic skeleton of logger system.
- [x] Implement the logger throughout the codebase.
- [x] Configure log levels and outputs for different environments.
